-- Bulk load of the Palestine Scholarship Database spreadsheet
-- (22 initiatives). Rows are published and idempotent: any programme whose
-- website already exists in `programmes` is skipped, so this is safe to
-- re-run and will not duplicate entries from 0001_programmes.sql.
-- Run in the Supabase SQL editor.

insert into programmes (
  university, country, city, programme_name, programme_type, target_group,
  degree_level, coverage, estimated_opening, estimated_deadline, academic_year,
  language, main_eligibility, required_documents, status, website, contact,
  notes, is_published, last_verified_at
)
select v.*
from (
  values
  (
    'Daughters for Life Foundation',
    'Canada / Belgium / partner countries',
    null,
    'Daughters for Life Scholarships',
    'Scholarship',
    'Palestinian students',
    array['Bachelor', 'Master''s'],
    'Full tuition, housing and meals; travel in the verified Antwerp award.',
    null,
    '2026/27 closed; 2027/28 dates not yet confirmed.',
    null,
    null,
    'Women from Palestine who demonstrate financial need and meet partner admission criteria.',
    null,
    'closed',
    'https://daughtersforlife.com/programs/scholarship/',
    null,
    'West Bank: Palestine included; no Gaza-only restriction. Recurrence: Recurring cohorts; 2026/27 partner award verified. Note: Partner awards and incidental costs differ. Retain full packages only. Additional source: https://www.uantwerpen.be/en/study/scholarships/scholarships-with-uantwerp-participation/dfl-uantwerp/',
    true,
    current_date
  ),
  (
    'University of Oxford (Rhodes Trust)',
    'UK',
    null,
    'Rhodes Scholarship – SJLP',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    'Oxford fees and living stipend; visa, health surcharge and travel support.',
    null,
    '2027 entry closed 27 Aug 2026. Next dates not announced.',
    null,
    null,
    'Palestinian constituency connection, academic excellence and cycle-specific age/education rules.',
    null,
    'closed',
    'https://www.rhodeshouse.ox.ac.uk/scholarships/applications/syria-jordan-lebanon-and-palestine/',
    null,
    'West Bank: Palestinian candidates eligible, including West Bank. Recurrence: Provider explicitly offers SJLP scholarships each year. Note: Check current age limits and eligible Oxford courses. Additional source: https://www.rhodeshouse.ox.ac.uk/scholarships/',
    true,
    current_date
  ),
  (
    'University of Cambridge',
    'UK',
    null,
    'Bseisu–University of Cambridge Scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full fees and living costs.',
    null,
    '2026/27 closed; 2027/28 information due autumn 2026.',
    null,
    null,
    'Applicants from Palestine, Lebanon, Jordan or Syria; STEM priority.',
    null,
    'closed',
    'https://www.bseisufoundation.org/scholarships',
    null,
    'West Bank: Palestine included; no Gaza-only restriction. Recurrence: 2026/27 award and 2027/28 update confirmed by provider. Note: Apply through Cambridge funding process. Additional source: https://www.bseisufoundation.org/bseisu-cambridge',
    true,
    current_date
  ),
  (
    'University of Oxford',
    'UK',
    null,
    'Bseisu–Oxford Energy Systems Scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full fees and living costs.',
    null,
    '2026/27 closed; 2027/28 information due autumn 2026.',
    null,
    null,
    'Applicants from Palestine, Lebanon, Jordan or Syria to MSc Energy Systems.',
    null,
    'closed',
    'https://www.bseisufoundation.org/scholarships',
    null,
    'West Bank: Palestine included; no Gaza-only restriction. Recurrence: 2026/27 award and 2027/28 update confirmed by provider. Note: Apply by the course funding deadline; no separate scholarship application. Additional source: https://www.bseisufoundation.org/bseisu-oxford',
    true,
    current_date
  ),
  (
    'Chevening (UK Government)',
    'UK',
    null,
    'Chevening Scholarship – Palestine (including Bseisu partner awards)',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full tuition, monthly living stipend, economy return travel, visa and arrival/departure allowances.',
    null,
    'OPEN: 6 Oct 2026, 11:00 UTC, for 2027/28.',
    null,
    null,
    'Eligible Palestinian citizen; degree completed at least two years before deadline; 2,800 post-degree work hours; apply to three eligible courses; two-year return requirement.',
    null,
    'open',
    'https://www.chevening.org/scholarship/palestine/',
    null,
    'West Bank: Palestine route includes West Bank; Gaza-only restriction absent. Recurrence: Annual programme; 2027/28 open. Bseisu funds five partner awards per year. Note: Bseisu STEM route merged here; automatic partner consideration. MBA tuition capped at GBP 22,000: retain only offers with full fee coverage. Existing Master’s permitted; prior UK government-funded study restrictions apply. Additional source: https://www.chevening.org/resource-hub/guidance/eligibility/
https://www.chevening.org/faqs/what-does-a-chevening-scholarship-cover/
https://www.chevening.org/scholarships/guidance/courses/
https://www.bseisufoundation.org/bseisu-chevening',
    true,
    current_date
  ),
  (
    'Albukhary International University',
    'Malaysia',
    null,
    'Albukhary International University – full scholarship',
    'Scholarship',
    'Palestinian students',
    array['Bachelor'],
    'Tuition, university accommodation and meal allowance.',
    null,
    '2026 international deadline was 31 Jul 2026; next dates not confirmed.',
    null,
    null,
    'Financially disadvantaged international applicants meeting age, income and admission rules.',
    null,
    'monitor',
    'https://aiu.edu.my/admissions-and-applications/',
    null,
    'West Bank: International route; no Gaza-only restriction published. Recurrence: Ongoing scholarship programme; 2025 activity and 2026 intake verified. Note: Select full scholarship. Confirm visa, travel and initial expenses in offer. Additional source: https://aiu.edu.my/PDF/Scholarship/Scholarship-Handbook-V4.pdf',
    true,
    current_date
  ),
  (
    'Irish Government (Irish Aid / AMIDEAST)',
    'Ireland',
    null,
    'Ireland–Palestine Scholarship Programme',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Fees, accommodation/living allowances, flights, insurance, visa and residence permit.',
    null,
    'OPEN: 20 Oct 2026, 23:59 Palestine time, for 2027/28.',
    null,
    null,
    'Palestinian/Jerusalem ID, resident in Palestine; minimum 80% or 3.0; no existing Master''s; English requirement.',
    null,
    'open',
    'https://www.amideast.org/west-bank/find-a-scholarship/graduate-study/ireland-palestine-scholarship-programme',
    null,
    'West Bank: Explicitly includes residents of Palestine with Palestinian or Jerusalem ID. Recurrence: 2026/27 and 2027/28 calls verified. Note: Previous spreadsheet''s 75% threshold is outdated; current minimum is 80%. Additional source: https://www.birzeit.edu/en/announcements/ireland-palestine-scholarship-programme-ipsp-ireland-scholarship-starting-year-2026',
    true,
    current_date
  ),
  (
    'University of Padua',
    'Italy',
    null,
    'University of Padua – Students at Risk',
    'Scholarship',
    'Palestinian students',
    array['Bachelor', 'Master''s'],
    'University fee waiver and EUR 12,000 gross annual living grant; travel to Italy.',
    null,
    '2026/27 closed 11 May 2026; next dates not announced.',
    null,
    null,
    'Refugee/protection status or documented personal risk; admission and language requirements.',
    null,
    'closed',
    'https://www.unipd.it/en/students-at-risk',
    null,
    'West Bank: International applicants at risk; not restricted to Gaza. Recurrence: Calls verified for 2024/25, 2025/26 and 2026/27. Note: Accommodation is arranged but paid by the student from the grant; renewal requires progress. Additional source: https://www.unipd.it/en/en/en/sites/en.unipd.it/files/Bando%20Students%20at%20Risk%202025%20ENG.pdf.pdf',
    true,
    current_date
  ),
  (
    'Gwangju Institute of Science and Technology (GIST)',
    'South Korea',
    null,
    'GIST – international graduate scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    'Full tuition plus student, meal and international allowances; research assistantships.',
    null,
    'Spring/fall graduate admissions; check live admission schedule.',
    null,
    null,
    'International graduate admission; allowance renewal depends on credits/GPA.',
    null,
    'monitor',
    'https://www.gist.ac.kr/iadm/html/sub04/0401.html',
    null,
    'West Bank: International route; no Gaza-only restriction published. Recurrence: Standing funding scheme for international graduate admissions; 2026 intake verified. Note: Housing paid from allowances. KRW 680,000 matriculation fee may apply; insurance only 60% supported; flight is one-way. Additional source: https://www.gist.ac.kr/iadm/main.html',
    true,
    current_date
  ),
  (
    'MEXT (Government of Japan)',
    'Japan',
    null,
    'MEXT – Research Students (Palestine route)',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    'Tuition exemption, monthly stipend and qualifying international airfare.',
    null,
    '2027 entry closed 4 Jun 2026; next dates not announced.',
    null,
    null,
    'Palestinian applicants satisfying MEXT degree, research and other annual requirements.',
    null,
    'closed',
    'https://www.ps.emb-japan.go.jp/itpr_en/Kenkyu2027.html',
    null,
    'West Bank: Official 2027 call explicitly gives West Bank and Jerusalem submission instructions. Recurrence: Embassy states approximately three awards to Palestinians each year. Note: Original ''MOFA'' entry resolved to MEXT. Undergraduate route not offered in Palestine for 2027. Additional source: https://www.ps.emb-japan.go.jp/itpr_en/studyinjapan.html',
    true,
    current_date
  ),
  (
    'University College London (UCL)',
    'UK',
    null,
    'UCL Global Undergraduate – tuition and maintenance awards only',
    'Scholarship',
    'Palestinian students',
    array['Bachelor'],
    'Full tuition, maintenance and a fixed additional-cost allowance.',
    null,
    '2026/27 closed 27 Apr 2026; next dates not announced.',
    null,
    null,
    'Low-income international applicants, overseas fee status and UCL application.',
    null,
    'closed',
    'https://www.ucl.ac.uk/scholarships/ucl-global-undergraduate-scholarship',
    null,
    'West Bank: Any country outside UK; includes West Bank Palestinians. Recurrence: Scheme operating since 2022; 2024 and 2026/27 full awards verified. Note: Only the 10 tuition-plus-maintenance awards qualify. Tuition-only and general Master''s awards removed. Additional source: https://www.ucl.ac.uk/teaching-learning/news/2024/jan/ucl-offers-33-international-scholarships-help-students-low-income-backgrounds',
    true,
    current_date
  ),
  (
    'Sabancı University',
    'Türkiye',
    null,
    'Sabancı University – full graduate scholarship only',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    'Tuition waiver, monthly stipend and dormitory support under full scholarship package.',
    null,
    '2026/27 admissions verified; deadlines vary by graduate school.',
    null,
    null,
    'International academic graduate applicants selected for full funding.',
    null,
    'monitor',
    'https://www.sabanciuniv.edu/en/graduate-scholarships-research-projects',
    null,
    'West Bank: International route; no Gaza-only restriction published. Recurrence: Standing graduate funding scheme and 2026/27 admissions verified. Note: Admission alone does not guarantee full funding. Professional degrees and tuition-only offers excluded. Additional source: https://fens.sabanciuniv.edu/en/financial-aid-and-scholarships-graduate-students',
    true,
    current_date
  ),
  (
    'Transilvania University of Brasov',
    'Romania',
    null,
    'Transilvania Academica Scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Tuition and registration/graduation fees, dormitory and RON 800/month.',
    null,
    '2026 closed 10 Apr 2026; next dates not announced.',
    null,
    null,
    'Non-EU/EEA citizens holding a Bachelor''s degree; merit-based selection.',
    null,
    'closed',
    'https://tas.unitbv.ro/',
    null,
    'West Bank: Non-EU/EEA route includes Palestinian applicants. Recurrence: Recurring scheme; 2025/26 and 2026/27 university references verified. Note: Travel and visa costs are explicitly self-funded. Annual academic progress required. Additional source: https://ww5.unitbv.ro/studenti/administrative/taxe/taxe-anul-universitar-2025-2026.html',
    true,
    current_date
  ),
  (
    'King Abdulaziz University',
    'Saudi Arabia',
    null,
    'King Abdulaziz University – external full scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    'Fully funded external award; tuition, stipend and university student services.',
    null,
    'Recurring admissions via university/Study in Saudi; exact next deadline not confirmed.',
    null,
    null,
    'International applicants residing outside Saudi Arabia; graduate academic and programme rules.',
    null,
    'monitor',
    'https://kau.edu.sa/en/page-legacy/international-student-scholarships',
    null,
    'West Bank: International external route; no Gaza-only restriction published. Recurrence: Standing external scholarship scheme; official pages updated in 2025 and 2026. Note: Apply specifically for funded external admission. Verify programme, housing and travel entitlements in award. Additional source: https://www.kau.edu.sa/en/page/scholarship',
    true,
    current_date
  ),
  (
    'Tsinghua University (Schwarzman Scholars)',
    'China',
    null,
    'Schwarzman Scholars Program – China',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full tuition, room and board, travel, insurance and stipend.',
    null,
    '2027/28 closed. Next global applications: Apr–Sep 2027 for Aug 2028 entry (2028/29). Exact days not yet published.',
    null,
    null,
    'Bachelor’s completed by 1 Aug of entry year; age at least 18 and under 29 on 1 Aug 2028 for next cohort; leadership and English proficiency.',
    null,
    'closed',
    'https://www.schwarzmanscholars.org/admissions/',
    null,
    'West Bank: All nationalities; no Gaza-only restriction. Recurrence: Annual selection explicitly confirmed; next 2028/29 global cycle announced. Note: Already in supplied file; retained once and updated 27 Sep 2026. Global application route for Palestinian candidates. Age cut-off is strict. Additional source: https://www.schwarzmanscholars.org/about/',
    true,
    current_date
  ),
  (
    'University of Sydney',
    'Australia',
    null,
    'Australian Government RTP – University of Sydney (stipend + fee offset)',
    'Scholarship',
    'Palestinian students',
    array['Master''s', 'PhD'],
    '100% tuition and stipend (AUD 42,754 in 2026; AUD 44,293 in 2027), OSHC and allowances.',
    null,
    'Next published deadline: 18 Dec 2026 for research periods 3–4, 2027. Periods 1–2, 2027 closed 11 Sep 2026.',
    null,
    null,
    'International higher-degree research applicants; competitive merit selection.',
    null,
    'closed',
    'https://www.sydney.edu.au/scholarships/australian-government-research-training-program/rtp-international.html',
    null,
    'West Bank: International route; no Gaza-only restriction published. Recurrence: 2026 and 2027 stipend rates and continuing application rounds published. Note: Apply for research admission AND submit scholarship form. Stipend award includes fee offset; fee-only awards excluded. RTP is already represented here and at Flinders, so no generic duplicate added. Additional source: https://www.education.gov.au/research-block-grants/research-training-program',
    true,
    current_date
  ),
  (
    'Rotary Foundation',
    'Multiple host countries',
    null,
    'Rotary Peace Fellowships',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Tuition/fees, room and board, round-trip travel and field-study expenses.',
    null,
    'Next 2028/29 application opens Feb 2027.',
    null,
    null,
    'Peace/development experience and leadership; Master''s normally requires at least three years'' relevant experience.',
    null,
    'monitor',
    'https://www.rotary.org/en/get-involved/our-programs/peace-fellowships',
    null,
    'West Bank: Applicants worldwide; not Gaza-only. Centre-specific conditions apply. Recurrence: Provider explicitly awards fellowships each year. Note: Certificate and Master''s routes have different eligibility and host locations. Additional source: https://www.rotary.org/get-involved/our-programs/peace-fellowships/peace-fellowships-masters-degree-programs',
    true,
    current_date
  ),
  (
    'Flinders University',
    'Australia',
    null,
    'Australian Government RTP – Flinders (International)',
    'Scholarship',
    'Palestinian students',
    array['PhD'],
    'Full fee offset, AUD 36,061 annual stipend (2026), OSHC and eligible relocation support.',
    null,
    '2026 round closed 18 Jun 2026; next international round not announced.',
    null,
    null,
    'Overseas citizens except New Zealand; no Australian citizenship/permanent residence; research admission.',
    null,
    'closed',
    'https://www.flinders.edu.au/scholarships/australian-government-research-training-program-scholarship-international',
    null,
    'West Bank: International route; no Gaza-only restriction published. Recurrence: Annual competitive programme; current 2026 round and earlier award rules verified. Note: Current page specifies up to 3.5 years for a research doctorate; supervisor support required. Relocation/airfare allowance up to AUD 1,485 after arrival, with receipts. Additional source: https://www.flinders.edu.au/international/apply/apply-research-degree/scholarships-fees',
    true,
    current_date
  ),
  (
    'University of Malta',
    'Malta',
    null,
    'University of Malta – Palestinian nationals scholarships',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Tuition, EUR 1,300/month, return travel up to EUR 1,000 and visa costs up to EUR 350.',
    null,
    '2026/27 closed 5 Jun 2026; next call not announced.',
    null,
    null,
    'Palestinian national resident in Palestine; full course acceptance; intent to return; no EU dual nationality.',
    null,
    'closed',
    'https://www.um.edu.mt/study/feesfunding/scholarships/palestinianscholarships/',
    null,
    'West Bank: West Bank eligible; current call cannot consider Gaza applications due to exit/visa constraints. Recurrence: Programme established 2014; repeated 2022, 2024 and 2026 calls verified. Note: Student pays costs above caps and needs initial settling-in savings. Course list has changed. Additional source: https://www.um.edu.mt/newspoint/notices/opportunities/2022/05/scholarships-for-palestinian-nationals',
    true,
    current_date
  ),
  (
    'Durham University',
    'UK',
    null,
    'Durham Palestine Educational Trust Scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full tuition from Durham; accommodation, living expenses, travel to UK and necessary visa costs from the Trust.',
    null,
    '2026 closed 30 Mar 2026. 2027 Master’s deadline not yet confirmed.',
    null,
    null,
    'Resident and family normally resident in West Bank/Gaza; degree from a West Bank/Gaza university; minimum 80% / 3.0 / B; English evidence, Durham offer and financial need.',
    null,
    'closed',
    'https://durhampalestine.webspace.durham.ac.uk/scholarships/',
    null,
    'West Bank: Explicitly includes West Bank residents and university graduates. Recurrence: Long-running programme since 1984; 2026 Master’s call and preparation for 2027 applicants published. Note: No previous Master’s or university study outside West Bank/Gaza (short courses excepted). Return required. Provider page mixes 2025/2026 labels; reconfirm next-cycle rules. Additional source: https://durhampalestine.webspace.durham.ac.uk/scholarships/howtoapply/
https://durhampalestine.webspace.durham.ac.uk/scholarships/ieltsscholarship/
https://durhampalestine.webspace.durham.ac.uk/about-us/',
    true,
    current_date
  ),
  (
    'Saïd Foundation',
    'UK',
    null,
    'Saïd Foundation Scholarship',
    'Scholarship',
    'Palestinian students',
    array['Master''s'],
    'Full tuition and maintenance, arrival allowance, visa, health surcharge and one economy return flight.',
    null,
    'OPEN: 30 Oct 2026, 17:00 UK time, for 2027/28.',
    null,
    null,
    'Palestinian nationality and normal residence in a target country; normally UK 2:1-equivalent degree; relevant experience, leadership, English test and eligible course application.',
    null,
    'open',
    'https://saidfoundation.org/apply/',
    null,
    'West Bank: Palestine is a target country; West Bank applicants eligible. Recurrence: Foundation explicitly offers approximately 20–30 new scholarships annually. Note: “Saed” interpreted as Saïd Foundation. No age limit. Palestine grade guide 80–89%; lower grades sometimes considered. Application fees and family costs excluded; Oxford/Cambridge/partner funding arrangements differ. Additional source: https://saidfoundation.org/scholarship-faqs/',
    true,
    current_date
  ),
  (
    'Government of Türkiye',
    'Türkiye',
    null,
    'Türkiye Scholarships – Turkish Government (full-time)',
    'Scholarship',
    'Palestinian students',
    array['Bachelor', 'Master''s', 'PhD'],
    'Tuition, accommodation, health insurance, Turkish language year, entry/graduation airfare and monthly stipend: undergraduate TRY 6,500; Master’s 9,500; PhD 13,000.',
    null,
    '2026 closed 20 Feb. Published annual window: 10 Jan–20 Feb; await specific 2027 call.',
    null,
    null,
    'Minimum grades: 70% undergraduate, 75% graduate, 90% medicine/dentistry/pharmacy. Age under 21 undergraduate, under 30 Master’s, under 35 PhD; programme requirements apply.',
    null,
    'closed',
    'https://www.turkiyeburslari.gov.tr/fulltimeprograms',
    null,
    'West Bank: Citizens of all countries eligible except Turkish/former Turkish citizens; includes West Bank Palestinians. Recurrence: Provider explicitly states annual 10 January–20 February applications; 2026 government announcement verified. Note: Full-time package only; not short-term/research stipend-only schemes. Cannot already study at the same level in Türkiye. Turkish language requirement applies; graduate health sciences excluded. Additional source: https://cdnweb.turkiyeburslari.gov.tr/scholarshipsprograms
https://www.ytb.gov.tr/en/news/turkiye-scholarships-2026-applications-are-now-open',
    true,
    current_date
  )
) as v(
  university, country, city, programme_name, programme_type, target_group,
  degree_level, coverage, estimated_opening, estimated_deadline, academic_year,
  language, main_eligibility, required_documents, status, website, contact,
  notes, is_published, last_verified_at
)
where not exists (
  select 1 from programmes p where p.website = v.website
);
